/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An explanation about the purpose of this instance.
 */
export type TheTimeSchema = string;
export type PropertiesShoutcastersItems = TheFirstAnyOfSchema;
/**
 * An explanation about the purpose of this instance.
 */
export type TheFirstAnyOfSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheShoutcastersSchema = PropertiesShoutcastersItems[];
/**
 * An explanation about the purpose of this instance.
 */
export type ScheduleType = 'showcase' | 'matches';
/**
 * An explanation about the purpose of this instance.
 */
export type TheNextRoundSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type ThePlayersSchema = string[];

/**
 * Countdown component data
 */
export interface CountdownReplicant {
	time: TheTimeSchema;
	shoutcasters: TheShoutcastersSchema;
	type: ScheduleType;
	showcase: TheShowcaseSchema;
	matches: TheMatchesSchema;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheShowcaseSchema {
	nextRound: TheNextRoundSchema;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheMatchesSchema {
	players: ThePlayersSchema;
}
