/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An explanation about the purpose of this instance.
 */
export type TheWsUrlSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheWsStatusSchema = 'CLOSED' | 'CONNECTING' | 'OPEN' | 'CLOSING';
/**
 * An explanation about the purpose of this instance.
 */
export type TheAutomaticReconnectSchema = boolean;

export interface CurrentGosumemoryConnectionStatus {
	wsUrl: TheWsUrlSchema;
	wsStatus: TheWsStatusSchema;
	automaticReconnect: TheAutomaticReconnectSchema;
}
