/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ObsIndexedSceneItem = ObsSceneItem & {
	sceneIndex: number;
};
export type Scenes = ObsIndexedSceneItem[];

export interface ConnectedOBSData {
	scenes: Scenes;
	currentScene?: ObsSceneItem;
	/**
	 * Is a scene transition currently happening?
	 */
	sceneTransitionActive?: boolean;
}
export interface ObsSceneItem {
	sceneName: string;
	sceneUuid: string;
}
