/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * has settings for autoadvance and associated states
 */
export interface OBSSceneAutoAdvanceSettings {
	autoadvance: boolean;
	scenes: {
		gameplay: string;
		mappool: string;
	};
	nextTransition?: {
		time: number;
		sceneName: string;
	};
}
