/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type OBSWebsocketUrlSchema = string;
export type OBSWebsocketConnectionPassword = string;
export type OBSWebsocketConnectionStatusSchema = 'CLOSED' | 'CONNECTING' | 'OPEN' | 'CLOSING';
export type OBSAutomaticReconnectSchema = boolean;

export interface CurrentOBSConnectionStatus {
	wsUrl: OBSWebsocketUrlSchema;
	wsPassword: OBSWebsocketConnectionPassword;
	wsStatus: OBSWebsocketConnectionStatusSchema;
	automaticReconnect: OBSAutomaticReconnectSchema;
}
