/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An explanation about the purpose of this instance.
 */
export type TheIdSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheSetIdSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheArtistSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheTitleSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheDifficultySchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheCreatorSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheSRSchema = string;
export type LengthAfterApplyingMods = string;
export type LengthBeforeApplyingMods = number;
export type TheARSchema = string;
export type ARBeforeApplyingMods = number;
export type ODAfterApplyingMods = string;
export type ODBeforeApplyingMods = number;
export type CSAfterApplyingMods = string;
export type CSBeforeApplyingMods = number;
export type BPMAfterApplyingMods = string;
export type LettersAcronymsOfActiveMods = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheStageSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheIndexSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheCategorySchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheCoverUrlSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheLocalBackgroundPathSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheSongsFolderPathSchema = string;

/**
 * osu! Now Playing Component data
 */
export interface CurrentOsuSongReplicant {
	id?: TheIdSchema;
	setId?: TheSetIdSchema;
	artist: TheArtistSchema;
	title: TheTitleSchema;
	difficulty?: TheDifficultySchema;
	creator?: TheCreatorSchema;
	SR?: TheSRSchema;
	length?: LengthAfterApplyingMods;
	lengthRaw?: LengthBeforeApplyingMods;
	AR?: TheARSchema;
	ARRaw?: ARBeforeApplyingMods;
	OD?: ODAfterApplyingMods;
	ODRaw?: ODBeforeApplyingMods;
	CS?: CSAfterApplyingMods;
	CSRaw?: CSBeforeApplyingMods;
	BPM?: BPMAfterApplyingMods;
	BPMRaw?: BPMBeforeApplyingMods;
	mods?: LettersAcronymsOfActiveMods;
	stage?: TheStageSchema;
	index?: TheIndexSchema;
	category?: TheCategorySchema;
	coverUrl?: TheCoverUrlSchema;
	localBackgroundPath?: TheLocalBackgroundPathSchema;
	songsFolderPath?: TheSongsFolderPathSchema;
}
export interface BPMBeforeApplyingMods {
	min: number;
	max: number;
	common?: number;
	realtime?: number;
}
