/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An explanation about the purpose of this instance.
 */
export type TheArtistSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheTitleSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheDifficultySchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheCreatorSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheSRSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheLengthSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheODSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheARSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheCSSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheBPMSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheStageSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheIndexSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheCategorySchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheSetIdSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheCoverUrlSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheLocalBackgroundPathSchema = string;

export interface CurrentOsuSongOverrides {
	[k: string]: The75Schema;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface The75Schema {
	artist?: TheArtistSchema;
	title?: TheTitleSchema;
	difficulty?: TheDifficultySchema;
	creator?: TheCreatorSchema;
	SR?: TheSRSchema;
	length?: TheLengthSchema;
	OD?: TheODSchema;
	AR?: TheARSchema;
	CS?: TheCSSchema;
	BPM?: TheBPMSchema;
	stage?: TheStageSchema;
	index?: TheIndexSchema;
	category?: TheCategorySchema;
	setId?: TheSetIdSchema;
	coverUrl?: TheCoverUrlSchema;
	localBackgroundPath?: TheLocalBackgroundPathSchema;
}
