/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PropertiesChatItemsPropertiesTeam = 'left' | 'right' | 'bot' | 'unknown' | '';

export interface OsuTourneyData {
	state: 'unknown' | 'spectating' | 'results';
	scoresVisible: boolean;
	starsVisible: boolean;
	bestOf: number;
	teamName: {
		left: string;
		right: string;
	};
	stars: {
		left: number;
		right: number;
	};
	chat: ChatMessage[] | null;
	clients: {
		mods: string;
		score: number;
		unstableRate: number;
		hits300: number;
		hits100: number;
		hits50: number;
		hits0: number;
	}[];
	time: {
		firstObj: number;
		current: number;
		full: number;
		mp3: number;
	};
}
export interface ChatMessage {
	team: PropertiesChatItemsPropertiesTeam;
	time: string;
	name: string;
	messageBody: string;
}
