/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type TournamentScheduleData = {
	time: number;
	red_seed: number;
	blue_seed: number;
	red_team: string;
	red_flag: string;
	blue_team: string;
	blue_flag: string;
	streamer: string;
	stream: string;
	type: string;
}[];
