/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Scenes = ObsSceneItem[];

export interface ConnectedOBSData {
	scenes: Scenes;
}
export interface ObsSceneItem {
	sceneIndex: number;
	sceneName: string;
	sceneUuid: string;
}
