/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An explanation about the purpose of this instance.
 */
export type TheShowInterfaceSchema = boolean;
/**
 * An explanation about the purpose of this instance.
 */
export type TheGameSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheSkinSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheSongsSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheBassDensitySchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheStateSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheGameModeSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheIsChatEnabledSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheFirstObjSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheCurrentSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheFullSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheMp3Schema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheIdSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheSetSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheMd5Schema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheRankedStatusSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheArtistSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheArtistOriginalSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheTitleSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheTitleOriginalSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheMapperSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheDifficultySchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheARSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheCSSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheODSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheHPSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheSRSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheMinSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheMaxSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheMaxComboSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheFullSRSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheMemoryARSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheMemoryCSSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheMemoryODSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheMemoryHPSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheFullSchema1 = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheFolderSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheFileSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheBgSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAudioSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheNumSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheStrSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type The95Schema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type The96Schema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type The97Schema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type The98Schema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type The99Schema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type The100Schema = number;
export type PropertiesMenuPropertiesPpPropertiesStrains = TheFirstAnyOfSchema | TheStrainsSchema;
/**
 * An explanation about the purpose of this instance.
 */
export type TheFirstAnyOfSchema = null;
export type PropertiesMenuPropertiesPpPropertiesStrainsItems = TheFirstAnyOfSchema1 | TheSecondAnyOfSchema;
/**
 * An explanation about the purpose of this instance.
 */
export type TheFirstAnyOfSchema1 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheSecondAnyOfSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheStrainsSchema = PropertiesMenuPropertiesPpPropertiesStrainsItems[];
/**
 * An explanation about the purpose of this instance.
 */
export type TheGameModeSchema1 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheNameSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheScoreSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAccuracySchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheCurrentSchema1 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheMaxSchema1 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheNormalSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheSmoothSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type The0Schema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type The50Schema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type The100Schema1 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type The300Schema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheGekiSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheKatuSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheSliderBreaksSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheCurrentSchema2 = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheMaxThisPlaySchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheUnstableRateSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheHitErrorArraySchema = (TheFirstAnyOfSchema2 | TheSecondAnyOfSchema1)[] | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheFirstAnyOfSchema2 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheSecondAnyOfSchema1 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheCurrentSchema3 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheFcSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheMaxThisPlaySchema1 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheIsPressedSchema = boolean;
/**
 * An explanation about the purpose of this instance.
 */
export type TheCountSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheIsPressedSchema1 = boolean;
/**
 * An explanation about the purpose of this instance.
 */
export type TheCountSchema1 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheIsPressedSchema2 = boolean;
/**
 * An explanation about the purpose of this instance.
 */
export type TheCountSchema2 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheIsPressedSchema3 = boolean;
/**
 * An explanation about the purpose of this instance.
 */
export type TheCountSchema3 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheHasLeaderboardSchema = boolean;
/**
 * An explanation about the purpose of this instance.
 */
export type TheIsVisibleSchema = boolean;
/**
 * An explanation about the purpose of this instance.
 */
export type TheNameSchema1 = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheScoreSchema1 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheComboSchema1 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheMaxComboSchema1 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheModsSchema1 = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheH300Schema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheH100Schema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheH50Schema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheH0Schema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheTeamSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type ThePositionSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheIsPassingSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheSlotsSchema = null | Slots;
export type Name = string;
export type Score = number;
export type Combo = number;
export type Maxcombo = number;
export type Mods = string;
export type H300 = number;
export type H100 = number;
export type H50 = number;
export type H0 = number;
export type Team = number;
export type Position = number;
export type Ispassing = number;
export type Slots = Items[];
/**
 * An explanation about the purpose of this instance.
 */
export type The0Schema1 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type The50Schema1 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type The100Schema2 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type The300Schema1 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheNameSchema2 = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheScoreSchema2 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheMaxComboSchema2 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheNumSchema1 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheStrSchema1 = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheGekiSchema1 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheKatuSchema1 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheIpcStateSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheBestOFSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheLeftSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheRightSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheLeftSchema1 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheRightSchema1 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheScoreVisibleSchema = boolean;
/**
 * An explanation about the purpose of this instance.
 */
export type TheStarsVisibleSchema = boolean;
/**
 * An explanation about the purpose of this instance.
 */
export type TheChatSchema = TheItemsSchema[] | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheTeamSchema1 = 'left' | 'right' | 'bot' | '';
/**
 * An explanation about the purpose of this instance.
 */
export type TheTimeSchema1 = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheNameSchema3 = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheMessageBodySchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheLeftSchema2 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheRightSchema2 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheIpcClientsSchema = TheItemsSchema1[] | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheTeamSchema2 = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheNameSchema4 = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheCountrySchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheUserIDSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAccuracySchema1 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheRankedScoreSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type ThePlayCountSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheGlobalRankSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheTotalPPSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheGameModeSchema2 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheScoreSchema4 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheNameSchema5 = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAccuracySchema2 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type The0Schema2 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type The50Schema2 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type The100Schema3 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type The300Schema2 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheGekiSchema2 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheKatuSchema2 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheSliderBreaksSchema1 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheUnstableRateSchema1 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheCurrentSchema4 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheMaxSchema2 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheNumSchema2 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheStrSchema2 = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheNormalSchema1 = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheSmoothSchema1 = number;

/**
 * Current gosumemory data.
 */
export interface CurrentGosumemoryData {
	settings: TheSettingsSchema;
	menu: TheMenuSchema;
	gameplay: TheGameplaySchema;
	resultsScreen: TheResultsScreenSchema;
	tourney: TheTourneySchema;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheSettingsSchema {
	showInterface: TheShowInterfaceSchema;
	folders: TheFoldersSchema;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheFoldersSchema {
	game: TheGameSchema;
	skin: TheSkinSchema;
	songs: TheSongsSchema;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheMenuSchema {
	mainMenu: TheMainMenuSchema;
	state: TheStateSchema;
	gameMode: TheGameModeSchema;
	isChatEnabled: TheIsChatEnabledSchema;
	bm: TheBmSchema;
	mods: TheModsSchema;
	pp: ThePpSchema;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheMainMenuSchema {
	bassDensity: TheBassDensitySchema;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheBmSchema {
	time: TheTimeSchema;
	id: TheIdSchema;
	set: TheSetSchema;
	md5: TheMd5Schema;
	rankedStatus: TheRankedStatusSchema;
	metadata: TheMetadataSchema;
	stats: TheStatsSchema;
	path: ThePathSchema;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheTimeSchema {
	firstObj: TheFirstObjSchema;
	current: TheCurrentSchema;
	full: TheFullSchema;
	mp3: TheMp3Schema;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheMetadataSchema {
	artist: TheArtistSchema;
	artistOriginal?: TheArtistOriginalSchema;
	title: TheTitleSchema;
	titleOriginal?: TheTitleOriginalSchema;
	mapper: TheMapperSchema;
	difficulty: TheDifficultySchema;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheStatsSchema {
	AR: TheARSchema;
	CS: TheCSSchema;
	OD: TheODSchema;
	HP: TheHPSchema;
	SR: TheSRSchema;
	BPM: TheBPMSchema;
	maxCombo: TheMaxComboSchema;
	fullSR: TheFullSRSchema;
	memoryAR: TheMemoryARSchema;
	memoryCS: TheMemoryCSSchema;
	memoryOD: TheMemoryODSchema;
	memoryHP: TheMemoryHPSchema;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheBPMSchema {
	min: TheMinSchema;
	max: TheMaxSchema;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface ThePathSchema {
	full: TheFullSchema1;
	folder: TheFolderSchema;
	file: TheFileSchema;
	bg: TheBgSchema;
	audio: TheAudioSchema;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheModsSchema {
	num: TheNumSchema;
	str: TheStrSchema;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface ThePpSchema {
	'95': The95Schema;
	'96': The96Schema;
	'97': The97Schema;
	'98': The98Schema;
	'99': The99Schema;
	'100': The100Schema;
	strains: PropertiesMenuPropertiesPpPropertiesStrains;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheGameplaySchema {
	gameMode: TheGameModeSchema1;
	name: TheNameSchema;
	score: TheScoreSchema;
	accuracy: TheAccuracySchema;
	combo: TheComboSchema;
	hp: TheHpSchema;
	hits: TheHitsSchema;
	pp: ThePpSchema1;
	keyOverlay: TheKeyOverlaySchema;
	leaderboard: TheLeaderboardSchema;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheComboSchema {
	current: TheCurrentSchema1;
	max: TheMaxSchema1;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheHpSchema {
	normal: TheNormalSchema;
	smooth: TheSmoothSchema;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheHitsSchema {
	'0': The0Schema;
	'50': The50Schema;
	'100': The100Schema1;
	'300': The300Schema;
	geki: TheGekiSchema;
	katu: TheKatuSchema;
	sliderBreaks: TheSliderBreaksSchema;
	grade: TheGradeSchema;
	unstableRate: TheUnstableRateSchema;
	hitErrorArray: TheHitErrorArraySchema;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheGradeSchema {
	current: TheCurrentSchema2;
	maxThisPlay: TheMaxThisPlaySchema;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface ThePpSchema1 {
	current: TheCurrentSchema3;
	fc: TheFcSchema;
	maxThisPlay: TheMaxThisPlaySchema1;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheKeyOverlaySchema {
	k1: TheK1Schema;
	k2: TheK2Schema;
	m1: TheM1Schema;
	m2: TheM2Schema;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheK1Schema {
	isPressed: TheIsPressedSchema;
	count: TheCountSchema;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheK2Schema {
	isPressed: TheIsPressedSchema1;
	count: TheCountSchema1;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheM1Schema {
	isPressed: TheIsPressedSchema2;
	count: TheCountSchema2;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheM2Schema {
	isPressed: TheIsPressedSchema3;
	count: TheCountSchema3;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheLeaderboardSchema {
	hasLeaderboard: TheHasLeaderboardSchema;
	isVisible: TheIsVisibleSchema;
	ourplayer: TheOurplayerSchema;
	slots: TheSlotsSchema;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheOurplayerSchema {
	name: TheNameSchema1;
	score: TheScoreSchema1;
	combo: TheComboSchema1;
	maxCombo: TheMaxComboSchema1;
	mods: TheModsSchema1;
	h300: TheH300Schema;
	h100: TheH100Schema;
	h50: TheH50Schema;
	h0: TheH0Schema;
	team: TheTeamSchema;
	position: ThePositionSchema;
	isPassing: TheIsPassingSchema;
}
export interface Items {
	name: Name;
	score: Score;
	combo: Combo;
	maxCombo: Maxcombo;
	mods: Mods;
	h300: H300;
	h100: H100;
	h50: H50;
	h0: H0;
	team: Team;
	position: Position;
	isPassing: Ispassing;
	[k: string]: unknown;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheResultsScreenSchema {
	'0': The0Schema1;
	'50': The50Schema1;
	'100': The100Schema2;
	'300': The300Schema1;
	name: TheNameSchema2;
	score: TheScoreSchema2;
	maxCombo: TheMaxComboSchema2;
	mods: TheModsSchema2;
	geki: TheGekiSchema1;
	katu: TheKatuSchema1;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheModsSchema2 {
	num: TheNumSchema1;
	str: TheStrSchema1;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheTourneySchema {
	manager: TheManagerSchema;
	ipcClients: TheIpcClientsSchema;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheManagerSchema {
	ipcState: TheIpcStateSchema;
	bestOF: TheBestOFSchema;
	teamName: TheTeamNameSchema;
	stars: TheStarsSchema;
	bools: TheBoolsSchema;
	chat: TheChatSchema;
	gameplay: TheGameplaySchema1;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheTeamNameSchema {
	left: TheLeftSchema;
	right: TheRightSchema;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheStarsSchema {
	left: TheLeftSchema1;
	right: TheRightSchema1;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheBoolsSchema {
	scoreVisible: TheScoreVisibleSchema;
	starsVisible: TheStarsVisibleSchema;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheItemsSchema {
	team: TheTeamSchema1;
	time: TheTimeSchema1;
	name: TheNameSchema3;
	messageBody: TheMessageBodySchema;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheGameplaySchema1 {
	score: TheScoreSchema3;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheScoreSchema3 {
	left: TheLeftSchema2;
	right: TheRightSchema2;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheItemsSchema1 {
	team: TheTeamSchema2;
	spectating: TheSpectatingSchema;
	gameplay: TheGameplaySchema2;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheSpectatingSchema {
	name: TheNameSchema4;
	country: TheCountrySchema;
	userID: TheUserIDSchema;
	accuracy: TheAccuracySchema1;
	rankedScore: TheRankedScoreSchema;
	playCount: ThePlayCountSchema;
	globalRank: TheGlobalRankSchema;
	totalPP: TheTotalPPSchema;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheGameplaySchema2 {
	gameMode: TheGameModeSchema2;
	score: TheScoreSchema4;
	name: TheNameSchema5;
	accuracy: TheAccuracySchema2;
	hits: TheHitsSchema1;
	combo: TheComboSchema2;
	mods: TheModsSchema3;
	hp: TheHpSchema1;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheHitsSchema1 {
	'0': The0Schema2;
	'50': The50Schema2;
	'100': The100Schema3;
	'300': The300Schema2;
	geki: TheGekiSchema2;
	katu: TheKatuSchema2;
	sliderBreaks: TheSliderBreaksSchema1;
	unstableRate: TheUnstableRateSchema1;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheComboSchema2 {
	current: TheCurrentSchema4;
	max: TheMaxSchema2;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheModsSchema3 {
	num: TheNumSchema2;
	str: TheStrSchema2;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheHpSchema1 {
	normal: TheNormalSchema1;
	smooth: TheSmoothSchema1;
}
