/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PropertiesAutopickNextColor = 'red' | 'blue';

/**
 * has settings for autopick and associated states
 */
export interface TournamentPicksAndBansSettings {
	autopick: {
		enabled: boolean;
		requiredBans: number;
		nextColor: PropertiesAutopickNextColor;
		[k: string]: unknown;
	};
}
