/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PropertiesPickbanType = 'pick' | 'ban';

export interface TournamentPicksAndBans {
	[k: string]: PropertiesPickban;
}
/**
 * This interface was referenced by `TournamentPicksAndBans`'s JSON-Schema definition
 * via the `patternProperty` "^[0-9]+$".
 */
export interface PropertiesPickban {
	color: 'red' | 'blue';
	type: PropertiesPickbanType;
	time: number;
	beatmap_id: number;
}
