/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type TournamentTeamsData = TournamentTeam[];

export interface TournamentTeam {
	team: string;
	flag: string;
	seed: number;
	players: {
		id: number;
		username: string;
		captain: boolean;
	}[];
}
